# Generated by Django 5.0.6 on 2024-06-19 18:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(unique=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(20)])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(validators=[django.core.validators.MinLengthValidator(8)])),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(validators=[django.core.validators.MaxLengthValidator(200)])),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)])),
                ('priceBy', models.CharField(choices=[('NIGHT', 'NIGHT'), ('GUEST', 'GUEST')])),
                ('max_guests', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('description', models.CharField(validators=[django.core.validators.MaxLengthValidator(400)])),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airbnb.user')),
            ],
        ),
    ]
